Repository kaushikd207/TimeManager, pull requests merged in 2021-10, with the labels that each got.

#1 Update index.html
  index.html
Labels: hactoberfest-accepted, hactoberfest2021

#2 Update index.html
  index.html
Labels: hactoberfest-accepted, hactoberfest2021

#3 Update index.html
  index.html
Labels: hactoberfest, hactoberfest-accepted, hactoberfest2021

#4 update
  index.html
Labels: hactoberfest, hactoberfest-accepted, hactoberfest2021

#5 Create README.md
  README.md
Labels: hactoberfest-accepted

#6 Update index.html
  index.html
Labels: hactoberfest-accepted

#7 Update index.html
  index.html
Labels: hactoberfest-accepted

#8 Update index.html
  index.html
Labels: hacktoberfest-accepted

#9 Update index.html
  index.html
Labels: hacktoberfest-accepted

#10 Update index.html
  index.html
Labels: hacktoberfest-accepted

#11 Update index.html
  index.html
Labels: hacktoberfest-accepted

#12 Update index.html
  index.html
Labels: hacktoberfest-accepted
